apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
    - name: my-container2
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /home/kshitij/pod
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
